name: ruben
layout_spectrum: 0.2897503988351673
typography_spectrum: 0.3695961094927043
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6635444664862007
  lightness: 0.794611872639507
  saturation: 0.8465147437527776
  rhythmicContrast: 0.827096733963117
purpose: []
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
